# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField()),
                ('uid2', models.IntegerField()),
            ],
            options={
                'db_table': 'firend',
            },
        ),
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者的id')),
                ('sid', models.IntegerField(verbose_name='被滑者的id')),
                ('stime', models.DateTimeField(auto_now_add=True, verbose_name='滑动时的时刻')),
                ('stype', models.CharField(choices=[('like', '喜欢'), ('super_like', '超级喜欢'), ('dislike', '不喜欢')], max_length=12, verbose_name='左滑dislike,右滑like,上滑super_like')),
            ],
            options={
                'db_table': 'swiper',
            },
        ),
    ]
