# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponenum', models.CharField(max_length=32, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=8, verbose_name='性别')),
                ('birthday', models.DateField(default='1911-1-1', verbose_name='出生年')),
                ('avatar', models.CharField(max_length=256, verbose_name='个人形象')),
                ('location', models.CharField(choices=[('北京市', '北京市'), ('上海市', '上海市'), ('天津市', '天津市'), ('重庆市', '重庆市'), ('河北省', '河北省'), ('山西省', '山西省'), ('辽宁省', '辽宁省'), ('吉林省', '吉林省'), ('黑龙江省', '黑龙江省'), ('江苏省', '江苏省'), ('浙江省', '浙江省'), ('安徽省', '安徽省'), ('福建省', '福建省'), ('江西省', '江西省'), ('山东省', '山东省'), ('河南省', '河南省'), ('湖北省', '湖北省'), ('湖南省', '湖南省'), ('广东省', '广东省'), ('海南省', '海南省'), ('四川省', '四川省'), ('贵州省', '贵州省'), ('云南省', '云南省'), ('陕西省', '陕西省'), ('甘肃省', '甘肃省'), ('青海省', '青海省'), ('台湾省', '台湾省')], max_length=20, verbose_name='常居地')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
